Update db pool helm chart template
dockup/helm-charts pull request #21
Opened 2019-02-01 12:31 UTC by roguesherlock

2019-02-03 07:40 UTC, iffyuva commented on db-pool/values.yaml
>  mysql:
Remember to remove mysql dependency later.

2019-02-03 07:41 UTC, iffyuva requested changes
There should be no new line in `dot-env-file` :| Otherwise PR looks good.

2019-02-04 05:55 UTC, roguesherlock commented
updated.

2019-02-07 03:33 UTC, iffyuva commented
Tested for BTT deployments.

2019-02-07 03:33 UTC, iffyuva approved these changes

2019-02-07 03:33 UTC, merged